"use client";
import Link from "next/link";
import { Heart, Menu, Search, ShoppingCart, UserRound } from "lucide-react";
import { useCart } from "@/store/cart";
import { useWishlist } from "@/store/wishlist";
const nav=["Mobiles","Laptops","Headphones","Earbuds","Sneakers","Skincare","Kitchen Appliances","Furniture","Sports","Books","Toys","Grocery"];
export function SiteHeader() {
  const { count: cartCount } = useCart();
  const { count: savedCount } = useWishlist();
  return <header className="sticky top-0 z-50"><div className="bg-[#1c2734] text-white"><div className="mx-auto flex h-16 max-w-[1360px] items-center gap-4 px-4"><button className="md:hidden" aria-label="Open navigation"><Menu size={21}/></button><Link href="/" className="shrink-0 text-xl font-black tracking-tight">VANTA<span className="text-[#d8ef72]">/</span><span className="block text-[9px] font-medium uppercase tracking-[.18em] text-white/55">Everyday market</span></Link><label className="relative hidden max-w-2xl flex-1 md:block"><span className="sr-only">Search products</span><input className="h-10 w-full rounded-full bg-white/10 px-5 pr-11 text-[13px] text-white placeholder:text-white/60" placeholder="Search products, brands and categories"/><Search className="absolute right-4 top-2.5 text-[#d8ef72]" size={18}/></label><Link href="/login" className="ml-auto rounded-full border border-white/30 px-5 py-2 text-center font-semibold hover:bg-white hover:text-[#1c2734]">Sign in</Link><Link href="/wishlist" className="relative hidden items-center gap-2 font-semibold lg:flex"><Heart size={17}/> Saved{savedCount>0 && <span className="absolute -right-2.5 -top-2 flex h-4 min-w-4 items-center justify-center rounded-full bg-[#d8ef72] px-1 text-[10px] font-bold text-[#1c2734]">{savedCount}</span>}</Link><Link href="/cart" className="relative flex items-center gap-2 rounded-full bg-[#d8ef72] px-4 py-2 font-semibold text-[#1c2734]"><ShoppingCart size={17}/> Cart{cartCount>0 && <span className="absolute -right-1.5 -top-1.5 flex h-5 min-w-5 items-center justify-center rounded-full bg-[#1c2734] px-1 text-[10px] font-bold text-white">{cartCount}</span>}</Link><Link href="/account" className="hidden xl:flex" aria-label="My account"><UserRound size={18}/></Link></div></div><nav aria-label="Primary categories" className="hidden border-b bg-[#f7f4ee] md:block"><div className="mx-auto flex h-11 max-w-[1360px] items-center justify-center gap-2 overflow-x-auto px-3">{nav.map(item=><Link key={item} href={`/shop?category=${encodeURIComponent(item)}`} className="whitespace-nowrap rounded-full px-3 py-1.5 text-[13px] font-medium hover:bg-[#e5ead9] hover:text-[#16815d]">{item}</Link>)}</div></nav></header>; }
